version: '3.8'
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - smart-garage-mysql2

  smart-garage-mysql2:
#    platform: linux/x86_64
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
#     MYSQL_DATABASE: smart-garage
      - MYSQL_USER=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234

#    volumes:
#      - mongo-data:/data/db
#  mongo-express:
#    image: mongo-express
#    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
#    ports:
#      - 8080:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#volumes:
#  mongo-data:
#    driver: local
